name: tog_v2
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  fluttertoast: 8.0.9
  flutter: 
    sdk: flutter
  flutter_svg: ^1.0.3

dev_dependencies: 
  flutter_lints: ^1.0.0
  lints: 1.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  #material design

  assets: 
    - assets/
    #assets

  fonts: 
    - family: OpenSans
      fonts: 
        - asset: fonts/open-sans.ttf
        - asset: fonts/open-sans-italic.ttf
          style: italic
  #kumpulan fonts

